name: Release

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'LICENSE.txt'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

env:
  BASE_URL: '/'
  GH_TOKEN: ${{ github.token }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Generate requirements file
        run: pip freeze > requirements.txt

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Find site-packages and zip Package
        run: |
          SITE_PACKAGES=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
          zip -r package.zip $SITE_PACKAGES/*

      - name: Add additional files to ZIP
        run: zip sailpoint_ocsf_lambda_package.zip sailpointEventCollector.py ocsf_map.json  normalized_terms.json  enum_mapping.json

      - name: Extract tag from GITHUB_REF
        id: tag
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"

      - name: Create release with versioning
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Release ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sailpoint_ocsf_lambda_package.zip
          asset_name: sailpoint_ocsf_lambda_package.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload cloudformation.yaml
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./cloudformation.yaml
          asset_name: cloudformation.yaml
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload sailpointOCSFGlueETL.py
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sailpointOCSFGlueETL.py
          asset_name: sailpoint_sailpointOCSFGlueETL.py
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload amazon_security_lake_integration_guide.docx
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./amazon_security_lake_integration_guide.docx
          asset_name: amazon_security_lake_integration_guide.docx
          asset_content_type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}